# Generated by Django 3.2.5 on 2022-03-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=100)),
                ('translate', models.CharField(max_length=100)),
                ('voice', models.FileField(upload_to='voices/')),
                ('language', models.CharField(max_length=100)),
                ('usage_count', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PassedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passed', to='translator.telegramaccount')),
                ('learned', models.ManyToManyField(related_name='learned_words', to='translator.Word')),
                ('words', models.ManyToManyField(related_name='passed_words', to='translator.Word')),
            ],
        ),
    ]
