# Generated by Django 3.2.5 on 2022-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='original',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
