# Generated by Django 3.2.5 on 2022-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_alter_word_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='word',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='voice',
            field=models.FileField(upload_to=''),
        ),
    ]
